<%
  solr_config = YAML.load(ERB.new(IO.read(Rails.root + 'config' + 'solr.yml')).result)[Rails.env].with_indifferent_access
  solr_url = solr_config[:url]
%>

default: &default
  adapter: solr
  url: <%= solr_url %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

