<%
  erb_result = ERB.new(IO.read(Rails.root + 'config' + 'solr.yml')).result
  solr_config = YAML.safe_load(erb_result, [], [], true) # allow YAML aliases
  solr_config = solr_config[Rails.env].with_indifferent_access
  solr_url = solr_config[:url]
%>

default: &default
  adapter: solr
  url: <%= solr_url %>

development:
  <<: *default

test: &test
  <<: *default

production:
  <<: *default

