# These settings can also be provided as environment variables, in the form, e.g.:
#    SETTING__ACTIVE_JOB_QUEUE__URL=http://...
#
# The mapping is described in `./config/initializers/config.rb`.
#
multitenancy:
  enabled: false
  default_host: # "%{tenant}.dev"
  admin_host:

ssl_configured: false

action_controller:
  asset_host:

redis:
  default_namespace: hyku

<%
  erb_result = ERB.new(IO.read(Rails.root + 'config' + 'solr.yml')).result
  solr_config = YAML.safe_load(erb_result, [], [], true) # allow YAML aliases
  solr_config = solr_config[Rails.env].with_indifferent_access
  solr_url = solr_config[:url]
  solr_name = 'hyku' # TODO: use `solr_config[:collection][:name]` instead
  solr_source_path = File.join(Rails.root, solr_config[:collection][:dir])
%>

solr:
  url: <%= solr_url %>
  configset: <%= solr_name %>
  configset_source_path: <%= solr_source_path %>
  collection_options:
    async:
    auto_add_replicas:
    collection:
      config_name: <%= solr_name %>
    create_node_set:
    max_shards_per_node:
    num_shards: 1
    replication_factor:
    router:
      name:
      field:
    rule:
    shards:
    snitch:

zookeeper:
  connection_str: "localhost:9983/configs"

active_job:
  queue_adapter: :async

active_job_queue:
  url:

s3:
  upload_bucket:

fits_path: "fits.sh"

google_analytics_id:

# Register here: http://www.geonames.org/manageaccount
geonames_username: 'jcoyne'
